This database contains wordlists collected as part of the [Daghestanian loans](https://ilcl.hse.ru/en/projects) project by the [Linguistic Convergence Laboratory](https://ilcl.hse.ru/en/) at NRU HSE. The aim of the 160-item shortlist, which is based on the [World Loanword Database questionnaire](https://wold.clld.org/), is to measure lexical contact on a micro-level. In other words, to quantify lexical convergence among the speech communities of minority languages on a village-level, and to detect fine-grained areal patterns beyond general observations on the spheres of influence of certain languages.

## The database

For now, the table shows source **Concepts** and target **Words**. Each target word is grouped in a similarity **Set** - a set of words that have the same meaning and look similar. In the future, data will be added on borrowing sources. Metadata includes the name of the **Village** where the word was recorded, the administrative **District** it is part of, the **Language** spoken there, and the **List ID**: these ID's correspond to a particular speaker or in some cases a written source like a dictionary. Data is accessible at: [Github/LingConLab/DagloanDatabase](https://github.com/LingConLab/DagloanDatabase).