source("pages/about.R")
source("pages/how-to-cite.R")
source("pages/the-database.R")
source("pages/mapsurv.R")
source("pages/maplex.R")
source("pages/sourceslex.R")
# source("pages/cluster-dendrogram.R")
source("pages/mediation-speakers.R")
source("pages/mediation-villages.R")

shinyServer(function(input, output) {
  output$about <- renderUI({aboutPage})
  output$howto <- renderUI({howPage})
  output$theDatabase <- renderUI({databasePage})
  output$mapsurv <- renderUI({mapSurvPage})
  output$maplex <- renderUI({mapLexPage})
  output$sourceslex <- renderUI({sourcesLexPage})
  # output$clusterDend <- renderUI({clusterDendPage})
  output$mediationSpeakers <- renderUI({mediationSpeakersPage})
  output$mediationVillages <- renderUI({mediationVillagesPage})
})