source("modules/UpSet-mediation.R")
source("pages/about.R")
source("pages/how-to-cite.R")
source("pages/the-database.R")
source("pages/mapsurv.R")
source("pages/maplex.R")
source("pages/sourceslex.R")
source("pages/cluster-dendrogram.R")
source("pages/cluster-dendrogram-strict.R")
source("pages/mediation-speakers.R")
source("pages/mediation-villages.R")
source("pages/mediation-turkic.R")
source("pages/mediation-azer.R")
source("pages/mediation-via-major.R")
source("pages/acknowledgements.R")
source("pages/references.R")

shinyServer(function(input, output) {
  
  output$about <- renderUI({aboutPage})
  output$howto <- renderUI({howPage})
  output$theDatabase <- renderUI({databasePage})
  output$mapsurv <- renderUI({mapSurvPage})
  output$maplex <- renderUI({mapLexPage})
  output$sourceslex <- renderUI({sourcesLexPage})
  output$clusterDend <- renderUI({clusterDendPage})
  output$clusterDendStrict <- renderUI({clusterDendStrictPage})
  output$mediationSpeakers <- renderUI({mediationSpeakersPage})
  output$mediationVillages <- renderUI({mediationVillagesPage})
  callModule(UpSetMediation, "turkictotalvillages", all_turkic_wide_total_village)
  callModule(UpSetMediation, "turkictotalregions", all_turkic_wide_total_language)
  output$mediationTurkicMajor <- renderUI({mediationTurkicMajorPage})
  callModule(UpSetMediation, "azervillages", all_turkic_wide_az_village)
  callModule(UpSetMediation, "azerregions", all_turkic_wide_az_language)
  output$acknowledgements <- renderUI({acknowledgementsPage})
  output$references <- renderUI({referencesPage})
})