referencesPage <- fluidPage(fluidRow(column(
  12,
  div(class="reflink", renderText("Auguie, Baptiste. 2017. GridExtra: Miscellaneous Functions for 'Grid' Graphics."), 
      tags$a(href="https://CRAN.R-project.org/package=gridExtra","https://CRAN.R-project.org/package=gridExtra.")),
  div(class="reflink", renderText("Barnier, Julien. 2019. Rmdformats: HTML Output Formats and Templates for 'Rmarkdown' Documents."), 
      tags$a(href="https://CRAN.R-project.org/package=rmdformats","https://CRAN.R-project.org/package=rmdformats.")),
  div(class="reflink", renderText("Boettiger, Carl. 2017. Knitcitations: Citations for 'Knitr' Markdown Files."), 
      tags$a(href="https://CRAN.R-project.org/package=knitcitations","https://CRAN.R-project.org/package=knitcitations.")),
  div(class="reflink", renderText("Galili, Tal. 2015. 'Dendextend: An R Package for Visualizing, Adjusting, and Comparing Trees of Hierarchical Clustering.' Bioinformatics."), 
      tags$a(href="https://doi.org/10.1093/bioinformatics/btv428","doi:10.1093/bioinformatics/btv428.")),
  div(class="reflink", renderText("Gehlenborg, Nils. 2017. UpSetR: A More Scalable Alternative to Venn and Euler Diagrams for Visualizing Intersecting Sets."), 
      tags$a(href="https://CRAN.R-project.org/package=UpSetR","https://CRAN.R-project.org/package=UpSetR.")),
  div(class="reflink", renderText("Haspelmath, Martin, and Uri Tadmor. 2009. Loanwords in the World's Languages: A Comparative Handbook. Walter de Gruyter")),
  div(class="reflink", renderText("Moroz, George. 2017. Lingtypology: Easy Mapping for Linguistic Typology."), 
      tags$a(href="https://CRAN.R-project.org/package=lingtypology","https://CRAN.R-project.org/package=lingtypology.")),
  div(class="reflink", renderText("R Core Team. 2019. R: A Language and Environment for Statistical Computing. Vienna, Austria: R Foundation for Statistical Computing."), 
      tags$a(href="https://www.R-project.org/","https://www.R-project.org.")),
  div(class="reflink", renderText("Sievert, Carson. 2018. Plotly for R."), 
      tags$a(href="https://plotly-r.com","https://plotly-r.com.")),
  div(class="reflink", renderText("Suzuki, Ryota, and Hidetoshi Shimodaira. 2015. Pvclust: Hierarchical Clustering with P-Values via Multiscale Bootstrap Resampling."), 
      tags$a(href="https://CRAN.R-project.org/package=pvclust","https://CRAN.R-project.org/package=pvclust.")),
  div(class="reflink", renderText("Wickham, Hadley. 2016. Ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York."), 
      tags$a(href="https://ggplot2.tidyverse.org","https://ggplot2.tidyverse.org.")),
  div(class="reflink", renderText("2017. Tidyverse: Easily Install and Load the 'Tidyverse'."), 
      tags$a(href="https://CRAN.R-project.org/package=tidyverse","https://CRAN.R-project.org/package=tidyverse.")),
  div(class="reflink", renderText("Xie, Yihui. 2014. 'Knitr: A Comprehensive Tool for Reproducible Research in R.' In Implementing Reproducible Computational Research, edited by Victoria Stodden, Friedrich Leisch, and Roger D. Peng. Chapman; Hall/CRC."), 
      tags$a(href="http://www.crcpress.com/product/isbn/9781466561595","http://www.crcpress.com/product/isbn/9781466561595.")),
  div(class="reflink", renderText("2015. Dynamic Documents with R and Knitr. 2nd ed. Boca Raton, Florida: Chapman; Hall/CRC."), 
      tags$a(href="https://yihui.name/knitr/","https://yihui.name/knitr.")),
  div(class="reflink", renderText("2019. Knitr: A General-Purpose Package for Dynamic Report Generation in R."), 
      tags$a(href="https://yihui.name/knitr/","https://yihui.name/knitr.")),
  div(class="reflink", renderText("Xie, Yihui, Joe Cheng, and Xianying Tan. 2019. DT: A Wrapper of the Javascript Library 'Datatables'."), 
      tags$a(href="https://CRAN.R-project.org/package=DT","https://CRAN.R-project.org/package=DT."))
)))